name: firebase_database_mocks
description: A Firebase real-time database mocks.
version: 0.1.0

repository: https://github.com/sitatec/firebase_database_mocks.git
homepage: https://github.com/sitatec/firebase_database_mocks.git
issue_tracker: https://github.com/sitatec/firebase_database_mocks/issues

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_database: ^4.4.0
  pedantic: ^1.9.0
  mockito: ^4.1.3
  firebase_core_platform_interface: ^2.1.0
  flutter_test:
    sdk: flutter
