name: firebase_database_mocks
description: A Firebase real-time database mocks.

version: 0.1.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_database: ^4.4.0
  pedantic: ^1.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.3
